/**
 * createGraphqlApolloAdapter
 *
 * Sugar over the per-slot identity helpers (`graphqlList`, `graphqlGet`,
 * `graphqlMutation`). Returns an adapter object whose `.schema()` method
 * accepts one config block per CRUD slot and produces a fully-typed
 * `CrudSchemata` ready to drop into `<CrudPanelView />` or `new CRUD()`.
 *
 * The raw helpers stay exported so power users can keep building partial
 * schemas, mix transports per resource, or skip the adapter instance
 * entirely.
 */

import type {
  CrudSchemata,
  CrudSchemataTypes,
  TransportBaseMutationOptions,
  TransportLazyQueryHookOptions,
  TransportOperationVariables,
  TransportQueryHookOptions,
} from '@crudx/core';

import {
  graphqlGet,
  graphqlList,
  graphqlMutation,
  GraphqlLazyQueryHook,
  GraphqlMutationHook,
  GraphqlQueryHook,
} from './index';

export interface GraphqlApolloAdapterConfig {
  /** Reserved for future shared defaults (default Apollo policies, …). */
}

/**
 * --------------------------
 * SLOT INPUTS
 * --------------------------
 *
 * Each slot binds an Apollo hook (typically generated by graphql-codegen
 * or hand-rolled) plus the `key` + `options` fields that live on
 * `CrudSchemata` slots.
 */
export interface GraphqlListSlotInput<
  TData = any,
  TVariables extends TransportOperationVariables = TransportOperationVariables
> {
  key: string;
  hook: GraphqlQueryHook<TData, TVariables>;
  options?: TransportQueryHookOptions<TData, TVariables>;
}

export interface GraphqlGetSlotInput<
  TData = any,
  TVariables extends TransportOperationVariables = TransportOperationVariables
> {
  key: string;
  hook: GraphqlLazyQueryHook<TData, TVariables>;
  options?: TransportLazyQueryHookOptions<TData, TVariables>;
}

export interface GraphqlMutationSlotInput<
  TData = any,
  TVariables extends TransportOperationVariables = TransportOperationVariables
> {
  key: string;
  hook: GraphqlMutationHook<TData, TVariables>;
  options?: TransportBaseMutationOptions<TData, TVariables>;
}

export interface GraphqlSchemaInput<TSchema extends CrudSchemataTypes = any> {
  list?: GraphqlListSlotInput<TSchema['list'][0], TSchema['list'][1]>;
  get?: GraphqlGetSlotInput<TSchema['get'][0], TSchema['get'][1]>;
  create?: GraphqlMutationSlotInput<
    TSchema['create'][0],
    TSchema['create'][1]
  >;
  update?: GraphqlMutationSlotInput<
    TSchema['update'][0],
    TSchema['update'][1]
  >;
  delete?: GraphqlMutationSlotInput<
    TSchema['delete'][0],
    TSchema['delete'][1]
  >;
  exports?: GraphqlMutationSlotInput<
    TSchema['exports'][0],
    TSchema['exports'][1]
  >;
}

export interface GraphqlApolloAdapter {
  /**
   * Builds a complete `CrudSchemata` from one config block per slot.
   * Each slot is wired through the matching identity helper under the
   * hood.
   */
  schema<TSchema extends CrudSchemataTypes>(
    input: GraphqlSchemaInput<TSchema>
  ): CrudSchemata<TSchema>;
}

export const createGraphqlApolloAdapter = (
  _config: GraphqlApolloAdapterConfig = {}
): GraphqlApolloAdapter => ({
  schema(input) {
    const out: CrudSchemata<any> = {};

    if (input.list) {
      out.list = {
        key: input.list.key,
        query: graphqlList(input.list.hook),
        options: input.list.options,
      };
    }

    if (input.get) {
      out.get = {
        key: input.get.key,
        query: graphqlGet(input.get.hook),
        options: input.get.options,
      };
    }

    if (input.create) {
      out.create = {
        key: input.create.key,
        query: graphqlMutation(input.create.hook),
        options: input.create.options,
      };
    }

    if (input.update) {
      out.update = {
        key: input.update.key,
        query: graphqlMutation(input.update.hook),
        options: input.update.options,
      };
    }

    if (input.delete) {
      out.delete = {
        key: input.delete.key,
        query: graphqlMutation(input.delete.hook),
        options: input.delete.options,
      };
    }

    if (input.exports) {
      out.exports = {
        key: input.exports.key,
        query: graphqlMutation(input.exports.hook),
        options: input.exports.options,
      };
    }

    return out;
  },
});
